baseURL = "https://www.invictokeerbergen.be"

[pagination]
    pagerSize = 10

[params]
    dateForm = "January 2, 2006"
    title = "Invicto Belgium VZW"
    shortSiteName="Invicto VZW"

[permalinks]
    nieuws = "/:section/:year/:month/:day/:slug/"

[markup.goldmark.renderer]
    hardWraps = true